__________________________________________________________________________________________________
RecurDyn V9R5 [Windows x64 System 9.5.10442.0] Analysis message file.
Copyright (C) 1997 - 2021 FunctionBay, Inc. All rights reserved.

Model file: TestDOE_GUI\TestDOE_GUI_0003\TestDOE_GUI_0003.rdyn [Model Name: Model1]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 1
    No. of Generalized Velocity                     = 1
    No. of Rigid Body                               = 1

Kinematic Degree of Freedom         = 1

Total array size                    = 2743
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 8
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 100
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-02
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 18:57:19 / 2023.6.12

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    6.133000E-03    5.120000E-04    1.299639E-07         100       300         0         0
    8.400000E-01    1.000000E-02    5.773284E-04         199       597         0         0
    1.000000E+00    1.000000E-02    2.642174E-03         215       645         0         0

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 18:57:19 / 2023.6.12
    Ending Time/Date       = 18:57:19 / 2023.6.12
    CPU Time = 0.6 Second (0 hr. 0 min 0.6 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
