__________________________________________________________________________________________________
RecurDyn2023 [Windows x64 System 10.1.11516.0] Analysis message file.
Copyright (C) 1997 - 2022 FunctionBay, Inc. All rights reserved.

RMD file: TestDOE_Batch_0010.rmd [Model Name: Model1]

_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 1
    No. of Generalized Velocity                     = 1
    No. of Rigid Body                               = 1

Kinematic Degree of Freedom         = 1

Total array size                    = 2733
Total memory size for array         = 0 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2023\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 1.000000000000000
    Step                           = 100
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-02
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03

_________________________________________________________________________________________________
Information of starting time
    Starting Time/Date     = 22:50:53 / 2023.6.12

_________________________________________________________________________________________________
Integrator Information
     Advanced Hybrid Implicit Integrator :: LDLT
        Numerical Damping          = 1.000000
        Linear Solver For MBD      = DENSE

_________________________________________________________________________________________________
Analysis processing...

        TIME          STEPSIZE        A_DELNRM          NJAC      NRES      ANRF     AINTF
    3.142010E-03    9.529958E-05    9.207801E+00         100       300         0         0
    5.000000E-01    1.000000E-02    5.940067E-15         200       600         0         0
    1.000000E+00    1.000000E-02    1.727266E-14         250       750         0         0

_________________________________________________________________________________________________
Analysis Time Information
    Starting Time/Date     = 22:50:53 / 2023.6.12
    Ending Time/Date       = 22:50:53 / 2023.6.12
    CPU Time = 0.2 Second (0 hr. 0 min 0.2 sec.)

_________________________________________________________________________________________________
Analysis is accomplished successfully

_________________________________________________________________________________________________
